version: '3'
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    container_name: zookeeper
    networks:
      - proposta-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - proposta-network
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: 'postgres:alpine'
    container_name: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - proposta-network
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    networks:
      - proposta-network
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
      - grafana
      - prometheus
      - jaeger
      - kafka
      - zookeeper
      - contas
      - analise
      - transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1

  analise:
    image: 'zupacademy/analise-financeira'
    container_name: analise
    ports:
      - 9999:9999
    networks:
      - proposta-network
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  contas:
    image: 'zupacademy/contas'
    container_name: contas
    ports:
      - 8888:8888
    networks:
      - proposta-network
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  proposta:
    image: mfkldev/proposta
    container_name: proposta
    ports:
      - 8081:8080
    networks:
      - proposta-network
    environment:
      MYSQL_DATABASE_URL: jdbc:mysql://db:3306/proposta?createDatabaseIfNotExist=true
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      ANALISE_API: http://analise:9999/api
      CARTOES_API: http://contas:8888/api
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/auth/realms/proposal
      KEYCLOAK_JWKS_URI: http://keycloak:8080/auth/realms/proposal/protocol/openid-connect/certs
    depends_on:
      - db
      - analise
      - contas
      - keycloak

  db:
    image: mysql
    container_name: db_proposta
    restart: always
    ports:
      - 3307:3306
    networks:
      - proposta-network
    environment:
      MYSQL_DATABASE: proposta
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  transacoes:
    image: zupacademy/transacoes
    container_name: transacoes
    ports:
      - 7777:7777
    networks:
      - proposta-network
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - proposta-network
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
     - prometheus-volume:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - proposta-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - proposta-network
    depends_on:
      - prometheus

  vault:
    image: vault:1.5.3
    container_name: vault
    ports:
      - 8200:8200
    networks:
      - proposta-network
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_TOKEN: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_ADDR: http://127.0.0.1:8200

networks:
  proposta-network:
    driver: bridge

volumes:
  mysql-data:
  grafana-volume:
  prometheus-volume:
  postgres-volume: